-- ANALYTICS QUERIES FOR THE INVESTMENT INTELLIGENCE PLATFORM

-- 1. TOP 10 COMPANIES BY AVERAGE STOCK PRICE
SELECT C.company_name, ROUND(AVG(SP.close_price),2) AS AVG_PRICE FROM STOCK_PRICES AS SP JOIN COMPANIES 
AS C ON SP.company_id = C.company_id GROUP BY C.company_name ORDER BY AVG_PRICE DESC LIMIT 10;

-- 2. SECTOR WITH HIGHEST AVERAGE STOCK PRICE
SELECT SECTOR, ROUND(AVG(SP.close_price),2) AS AVG_PRICE FROM STOCK_PRICES AS SP JOIN COMPANIES 
AS C ON SP.company_id = C.company_id GROUP BY C.sector ORDER BY AVG_PRICE DESC LIMIT 1;

-- 3. COMPANIES WITH AVERAGE STOCK PRICE GREATER THAN THE OVERALL AVERAGE
SELECT C.COMPANY_NAME, ROUND(AVG(SP.close_price),2) AS AVG_PRICE FROM STOCK_PRICES AS SP JOIN 
COMPANIES AS C ON SP.company_id= C.company_id GROUP BY C.company_name HAVING 
AVG(SP.close_price) > (SELECT AVG(close_price) FROM STOCK_PRICES);


-- 4. TOP 5 COMPANIES BY TRADE VOLUME
SELECT C.company_name, SUM(SP.volume) FROM COMPANIES AS C JOIN STOCK_PRICES AS SP ON C.company_id
= SP.company_id GROUP BY C.company_name ORDER BY SUM(SP.volume) DESC LIMIT 5;

-- 5. WHICH COUNTRY HAS THE HIGHEST AVERAGE STOCK PRICE?
SELECT COUNTRY, ROUND(AVG(SP.CLOSE_PRICE),2) FROM COMPANIES AS C JOIN STOCK_PRICES AS SP ON 
C.company_id = SP.company_id GROUP BY COUNTRY ORDER BY AVG(SP.close_price) DESC LIMIT 1;

-- 6. AVERAGE, MAX AND MIN STOCK PRICE BY SECTOR
SELECT SECTOR, ROUND(AVG(SP.CLOSE_PRICE),2), MAX(SP.CLOSE_PRICE), MIN(SP.CLOSE_PRICE) 
FROM COMPANIES AS C JOIN STOCK_PRICES AS SP ON C.company_id = SP.company_id GROUP BY SECTOR; 


