-- Which companies are the highest priced within their own sector? 
WITH RANKED_COMPANIES AS (SELECT C.COMPANY_NAME, C.SECTOR, AVG(SP.CLOSE_PRICE) AS AVG_CP, 
DENSE_RANK() OVER (PARTITION BY C.sector ORDER BY AVG(SP.CLOSE_PRICE) DESC) AS PRICE_RANK
FROM COMPANIES AS C JOIN STOCK_PRICES AS SP ON C.company_id = SP.company_id
GROUP BY C.company_name, C.sector)
SELECT COMPANY_NAME, SECTOR, ROUND(AVG_CP,2), PRICE_RANK FROM RANKED_COMPANIES 
WHERE PRICE_RANK = 1;


-- On which days did each company's price move the most?
WITH PRICE_MOVEMENTS AS (SELECT C.COMPANY_NAME, SP.trade_date, 
ABS(SP.CLOSE_PRICE - LAG(SP.CLOSE_PRICE) OVER (PARTITION BY C.company_id ORDER BY SP.trade_date)) AS PRICE_CHANGE
FROM COMPANIES AS C JOIN STOCK_PRICES AS SP ON C.company_id = SP.company_id)
SELECT COMPANY_NAME, trade_date, ROUND(PRICE_CHANGE,2) AS PRICE_CHANGE FROM PRICE_MOVEMENTS
WHERE PRICE_CHANGE IS NOT NULL ORDER BY PRICE_CHANGE DESC;

-- What is the short-term price trend for each company? 7-day moving average of close price per company
SELECT C.COMPANY_NAME, SP.TRADE_DATE, SP.CLOSE_PRICE,
ROUND(AVG(SP.CLOSE_PRICE) OVER (PARTITION BY C.company_id ORDER BY SP.TRADE_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),2) AS MOVING_AVG_7D
FROM COMPANIES AS C JOIN STOCK_PRICES AS SP ON C.company_id = SP.company_id
ORDER BY C.COMPANY_NAME, SP.TRADE_DATE; 

